services:
  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8080
      # Authentication is handled at the API Gateway level
    ports:
      - "50051:50051"  # gRPC port
      - "8080:8080"    # HTTP port
    networks:
      - postgres_network
      - gateway_shared_network

networks:
  postgres_network:
    driver: bridge
  gateway_shared_network:
    external: true
