services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_FORWARD_PORT}:5432"
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PGADMIN_FORWARD_PORT}:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
