// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: config/v1/config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	Scope_SYSTEM            Scope = 1 // System-wide default configuration. scope_id should be 'default'.
	Scope_PROJECT           Scope = 2 // Project-specific configuration.
	Scope_STORE             Scope = 3 // Store-specific configuration.
	Scope_USER              Scope = 4 // User-specific configuration.
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SYSTEM",
		2: "PROJECT",
		3: "STORE",
		4: "USER",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SYSTEM":            1,
		"PROJECT":           2,
		"STORE":             3,
		"USER":              4,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_config_v1_config_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_STRING                 FieldType = 1
	FieldType_INT                    FieldType = 2
	FieldType_FLOAT                  FieldType = 3
	FieldType_BOOLEAN                FieldType = 4
	FieldType_JSON                   FieldType = 5
	FieldType_ARRAY_STRING           FieldType = 6 // Example for an array type
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "INT",
		3: "FLOAT",
		4: "BOOLEAN",
		5: "JSON",
		6: "ARRAY_STRING",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"STRING":                 1,
		"INT":                    2,
		"FLOAT":                  3,
		"BOOLEAN":                4,
		"JSON":                   5,
		"ARRAY_STRING":           6,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_config_proto_enumTypes[1].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_config_v1_config_proto_enumTypes[1]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

// A unique identifier for a configuration set.
type ConfigIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Required. Name of the service owning the config (e.g., "payment-service").
	Scope         Scope                  `protobuf:"varint,2,opt,name=scope,proto3,enum=vn.dsai.config.v1.Scope" json:"scope,omitempty"`  // Required. The scope of the configuration.
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`             // (Optional) Config group (e.g., "database", "api-keys").
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`       // (Optional) Project ID (max 20 chars).
	StoreId       string                 `protobuf:"bytes,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`             // (Optional) Store ID (max 20 chars).
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // (Optional) User ID (max 36 chars, e.g., UUID).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigIdentifier) Reset() {
	*x = ConfigIdentifier{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigIdentifier) ProtoMessage() {}

func (x *ConfigIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigIdentifier.ProtoReflect.Descriptor instead.
func (*ConfigIdentifier) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigIdentifier) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigIdentifier) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *ConfigIdentifier) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ConfigIdentifier) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ConfigIdentifier) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ConfigIdentifier) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Represents a configuration version.
type ConfigVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier       *ConfigIdentifier      `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	LatestVersion    int32                  `protobuf:"varint,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	PublishedVersion int32                  `protobuf:"varint,4,opt,name=published_version,json=publishedVersion,proto3" json:"published_version,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy        string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigVersion) Reset() {
	*x = ConfigVersion{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersion) ProtoMessage() {}

func (x *ConfigVersion) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersion.ProtoReflect.Descriptor instead.
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigVersion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigVersion) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ConfigVersion) GetLatestVersion() int32 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *ConfigVersion) GetPublishedVersion() int32 {
	if x != nil {
		return x.PublishedVersion
	}
	return 0
}

func (x *ConfigVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ConfigVersion) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigVersion) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// A specific configuration field with its value.
type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                     // The key of the config (e.g., "database.postgres.connection_string").
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                   // The value, stored as a string.
	Type          FieldType              `protobuf:"varint,3,opt,name=type,proto3,enum=vn.dsai.config.v1.FieldType" json:"type,omitempty"`   // Data type to help clients parse the value.
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // (Optional)
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                       // (Optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigField) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ConfigField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Represents a complete configuration set at a specific version.
type ScopeConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo    *ConfigVersion         `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // The version number of the accompanying fields.
	Fields         []*ConfigField         `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScopeConfig) Reset() {
	*x = ScopeConfig{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeConfig) ProtoMessage() {}

func (x *ScopeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeConfig.ProtoReflect.Descriptor instead.
func (*ScopeConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ScopeConfig) GetVersionInfo() *ConfigVersion {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *ScopeConfig) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *ScopeConfig) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// A predefined choice for a configuration field, used for creating dropdowns in UIs.
type ValueOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // The actual value to be stored.
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // The human-readable label for the UI.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueOption) Reset() {
	*x = ValueOption{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueOption) ProtoMessage() {}

func (x *ValueOption) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueOption.ProtoReflect.Descriptor instead.
func (*ValueOption) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *ValueOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ValueOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Defines the schema for a single configuration field.
type ConfigFieldTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                                 // The key (e.g., "payment.provider.name").
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                               // The display name for UIs (e.g., "Payment Provider").
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                   // A helpful description for the user.
	Type          FieldType              `protobuf:"varint,4,opt,name=type,proto3,enum=vn.dsai.config.v1.FieldType" json:"type,omitempty"`                               // The data type (STRING, INT, etc.).
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`                             // Default value for this field.
	DisplayOn     []Scope                `protobuf:"varint,6,rep,packed,name=display_on,json=displayOn,proto3,enum=vn.dsai.config.v1.Scope" json:"display_on,omitempty"` // Defines which scopes can set this value (STORE, PROJECT, etc.).
	Options       []*ValueOption         `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`                                                           // A list of predefined options for this field.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFieldTemplate) Reset() {
	*x = ConfigFieldTemplate{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFieldTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFieldTemplate) ProtoMessage() {}

func (x *ConfigFieldTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFieldTemplate.ProtoReflect.Descriptor instead.
func (*ConfigFieldTemplate) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigFieldTemplate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigFieldTemplate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigFieldTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigFieldTemplate) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *ConfigFieldTemplate) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigFieldTemplate) GetDisplayOn() []Scope {
	if x != nil {
		return x.DisplayOn
	}
	return nil
}

func (x *ConfigFieldTemplate) GetOptions() []*ValueOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// A container that groups all field templates for a specific service_name and group_id.
type ConfigTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // Uniquely identifies the template (using service_name and group_id).
	Fields        []*ConfigFieldTemplate `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigTemplate) Reset() {
	*x = ConfigTemplate{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigTemplate) ProtoMessage() {}

func (x *ConfigTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigTemplate.ProtoReflect.Descriptor instead.
func (*ConfigTemplate) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigTemplate) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ConfigTemplate) GetFields() []*ConfigFieldTemplate {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type GetConfigByVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigByVersionRequest) Reset() {
	*x = GetConfigByVersionRequest{}
	mi := &file_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigByVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigByVersionRequest) ProtoMessage() {}

func (x *GetConfigByVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigByVersionRequest.ProtoReflect.Descriptor instead.
func (*GetConfigByVersionRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigByVersionRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetConfigByVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Fields        []*ConfigField         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"` // The user making the change.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateConfigRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *UpdateConfigRequest) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateConfigRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type PublishVersionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Identifier       *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	VersionToPublish int32                  `protobuf:"varint,2,opt,name=version_to_publish,json=versionToPublish,proto3" json:"version_to_publish,omitempty"`
	User             string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishVersionRequest) Reset() {
	*x = PublishVersionRequest{}
	mi := &file_config_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVersionRequest) ProtoMessage() {}

func (x *PublishVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVersionRequest.ProtoReflect.Descriptor instead.
func (*PublishVersionRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *PublishVersionRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *PublishVersionRequest) GetVersionToPublish() int32 {
	if x != nil {
		return x.VersionToPublish
	}
	return 0
}

func (x *PublishVersionRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_config_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteConfigRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type GetConfigHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryRequest) Reset() {
	*x = GetConfigHistoryRequest{}
	mi := &file_config_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryRequest) ProtoMessage() {}

func (x *GetConfigHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigHistoryRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type GetConfigHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*ConfigVersion       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryResponse) Reset() {
	*x = GetConfigHistoryResponse{}
	mi := &file_config_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryResponse) ProtoMessage() {}

func (x *GetConfigHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigHistoryResponse) GetVersions() []*ConfigVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ApplyConfigTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *ConfigTemplate        `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigTemplateRequest) Reset() {
	*x = ApplyConfigTemplateRequest{}
	mi := &file_config_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigTemplateRequest) ProtoMessage() {}

func (x *ApplyConfigTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigTemplateRequest.ProtoReflect.Descriptor instead.
func (*ApplyConfigTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyConfigTemplateRequest) GetTemplate() *ConfigTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *ApplyConfigTemplateRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetConfigTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *ConfigIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigTemplateRequest) Reset() {
	*x = GetConfigTemplateRequest{}
	mi := &file_config_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigTemplateRequest) ProtoMessage() {}

func (x *GetConfigTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetConfigTemplateRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigTemplateRequest) GetIdentifier() *ConfigIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\x11vn.dsai.config.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd3\x01\n" +
	"\x10ConfigIdentifier\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12.\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x18.vn.dsai.config.v1.ScopeR\x05scope\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12\x19\n" +
	"\bstore_id\x18\x05 \x01(\tR\astoreId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"\xec\x02\n" +
	"\rConfigVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12C\n" +
	"\n" +
	"identifier\x18\x02 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\x12%\n" +
	"\x0elatest_version\x18\x03 \x01(\x05R\rlatestVersion\x12+\n" +
	"\x11published_version\x18\x04 \x01(\x05R\x10publishedVersion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\xb0\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.vn.dsai.config.v1.FieldTypeR\x04type\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xb3\x01\n" +
	"\vScopeConfig\x12C\n" +
	"\fversion_info\x18\x01 \x01(\v2 .vn.dsai.config.v1.ConfigVersionR\vversionInfo\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x05R\x0ecurrentVersion\x126\n" +
	"\x06fields\x18\x03 \x03(\v2\x1e.vn.dsai.config.v1.ConfigFieldR\x06fields\"9\n" +
	"\vValueOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xab\x02\n" +
	"\x13ConfigFieldTemplate\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1c.vn.dsai.config.v1.FieldTypeR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x127\n" +
	"\n" +
	"display_on\x18\x06 \x03(\x0e2\x18.vn.dsai.config.v1.ScopeR\tdisplayOn\x128\n" +
	"\aoptions\x18\a \x03(\v2\x1e.vn.dsai.config.v1.ValueOptionR\aoptions\"\x95\x01\n" +
	"\x0eConfigTemplate\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\x12>\n" +
	"\x06fields\x18\x02 \x03(\v2&.vn.dsai.config.v1.ConfigFieldTemplateR\x06fields\"W\n" +
	"\x10GetConfigRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\"z\n" +
	"\x19GetConfigByVersionRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\xa6\x01\n" +
	"\x13UpdateConfigRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.vn.dsai.config.v1.ConfigFieldR\x06fields\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"\x9e\x01\n" +
	"\x15PublishVersionRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\x12,\n" +
	"\x12version_to_publish\x18\x02 \x01(\x05R\x10versionToPublish\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"Z\n" +
	"\x13DeleteConfigRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\"^\n" +
	"\x17GetConfigHistoryRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier\"X\n" +
	"\x18GetConfigHistoryResponse\x12<\n" +
	"\bversions\x18\x01 \x03(\v2 .vn.dsai.config.v1.ConfigVersionR\bversions\"o\n" +
	"\x1aApplyConfigTemplateRequest\x12=\n" +
	"\btemplate\x18\x01 \x01(\v2!.vn.dsai.config.v1.ConfigTemplateR\btemplate\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"_\n" +
	"\x18GetConfigTemplateRequest\x12C\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2#.vn.dsai.config.v1.ConfigIdentifierR\n" +
	"identifier*L\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\v\n" +
	"\aPROJECT\x10\x02\x12\t\n" +
	"\x05STORE\x10\x03\x12\b\n" +
	"\x04USER\x10\x04*p\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\a\n" +
	"\x03INT\x10\x02\x12\t\n" +
	"\x05FLOAT\x10\x03\x12\v\n" +
	"\aBOOLEAN\x10\x04\x12\b\n" +
	"\x04JSON\x10\x05\x12\x10\n" +
	"\fARRAY_STRING\x10\x062\xde\x06\n" +
	"\rConfigService\x12P\n" +
	"\tGetConfig\x12#.vn.dsai.config.v1.GetConfigRequest\x1a\x1e.vn.dsai.config.v1.ScopeConfig\x12V\n" +
	"\x0fGetLatestConfig\x12#.vn.dsai.config.v1.GetConfigRequest\x1a\x1e.vn.dsai.config.v1.ScopeConfig\x12b\n" +
	"\x12GetConfigByVersion\x12,.vn.dsai.config.v1.GetConfigByVersionRequest\x1a\x1e.vn.dsai.config.v1.ScopeConfig\x12k\n" +
	"\x10GetConfigHistory\x12*.vn.dsai.config.v1.GetConfigHistoryRequest\x1a+.vn.dsai.config.v1.GetConfigHistoryResponse\x12V\n" +
	"\fUpdateConfig\x12&.vn.dsai.config.v1.UpdateConfigRequest\x1a\x1e.vn.dsai.config.v1.ScopeConfig\x12\\\n" +
	"\x0ePublishVersion\x12(.vn.dsai.config.v1.PublishVersionRequest\x1a .vn.dsai.config.v1.ConfigVersion\x12N\n" +
	"\fDeleteConfig\x12&.vn.dsai.config.v1.DeleteConfigRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x13ApplyConfigTemplate\x12-.vn.dsai.config.v1.ApplyConfigTemplateRequest\x1a!.vn.dsai.config.v1.ConfigTemplate\x12c\n" +
	"\x11GetConfigTemplate\x12+.vn.dsai.config.v1.GetConfigTemplateRequest\x1a!.vn.dsai.config.v1.ConfigTemplateBGZEgithub.com/digitalsolutionsai/scope-config-service/config/v1;configv1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_config_v1_config_proto_goTypes = []any{
	(Scope)(0),                         // 0: vn.dsai.config.v1.Scope
	(FieldType)(0),                     // 1: vn.dsai.config.v1.FieldType
	(*ConfigIdentifier)(nil),           // 2: vn.dsai.config.v1.ConfigIdentifier
	(*ConfigVersion)(nil),              // 3: vn.dsai.config.v1.ConfigVersion
	(*ConfigField)(nil),                // 4: vn.dsai.config.v1.ConfigField
	(*ScopeConfig)(nil),                // 5: vn.dsai.config.v1.ScopeConfig
	(*ValueOption)(nil),                // 6: vn.dsai.config.v1.ValueOption
	(*ConfigFieldTemplate)(nil),        // 7: vn.dsai.config.v1.ConfigFieldTemplate
	(*ConfigTemplate)(nil),             // 8: vn.dsai.config.v1.ConfigTemplate
	(*GetConfigRequest)(nil),           // 9: vn.dsai.config.v1.GetConfigRequest
	(*GetConfigByVersionRequest)(nil),  // 10: vn.dsai.config.v1.GetConfigByVersionRequest
	(*UpdateConfigRequest)(nil),        // 11: vn.dsai.config.v1.UpdateConfigRequest
	(*PublishVersionRequest)(nil),      // 12: vn.dsai.config.v1.PublishVersionRequest
	(*DeleteConfigRequest)(nil),        // 13: vn.dsai.config.v1.DeleteConfigRequest
	(*GetConfigHistoryRequest)(nil),    // 14: vn.dsai.config.v1.GetConfigHistoryRequest
	(*GetConfigHistoryResponse)(nil),   // 15: vn.dsai.config.v1.GetConfigHistoryResponse
	(*ApplyConfigTemplateRequest)(nil), // 16: vn.dsai.config.v1.ApplyConfigTemplateRequest
	(*GetConfigTemplateRequest)(nil),   // 17: vn.dsai.config.v1.GetConfigTemplateRequest
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
}
var file_config_v1_config_proto_depIdxs = []int32{
	0,  // 0: vn.dsai.config.v1.ConfigIdentifier.scope:type_name -> vn.dsai.config.v1.Scope
	2,  // 1: vn.dsai.config.v1.ConfigVersion.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	18, // 2: vn.dsai.config.v1.ConfigVersion.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: vn.dsai.config.v1.ConfigVersion.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: vn.dsai.config.v1.ConfigField.type:type_name -> vn.dsai.config.v1.FieldType
	3,  // 5: vn.dsai.config.v1.ScopeConfig.version_info:type_name -> vn.dsai.config.v1.ConfigVersion
	4,  // 6: vn.dsai.config.v1.ScopeConfig.fields:type_name -> vn.dsai.config.v1.ConfigField
	1,  // 7: vn.dsai.config.v1.ConfigFieldTemplate.type:type_name -> vn.dsai.config.v1.FieldType
	0,  // 8: vn.dsai.config.v1.ConfigFieldTemplate.display_on:type_name -> vn.dsai.config.v1.Scope
	6,  // 9: vn.dsai.config.v1.ConfigFieldTemplate.options:type_name -> vn.dsai.config.v1.ValueOption
	2,  // 10: vn.dsai.config.v1.ConfigTemplate.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	7,  // 11: vn.dsai.config.v1.ConfigTemplate.fields:type_name -> vn.dsai.config.v1.ConfigFieldTemplate
	2,  // 12: vn.dsai.config.v1.GetConfigRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	2,  // 13: vn.dsai.config.v1.GetConfigByVersionRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	2,  // 14: vn.dsai.config.v1.UpdateConfigRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	4,  // 15: vn.dsai.config.v1.UpdateConfigRequest.fields:type_name -> vn.dsai.config.v1.ConfigField
	2,  // 16: vn.dsai.config.v1.PublishVersionRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	2,  // 17: vn.dsai.config.v1.DeleteConfigRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	2,  // 18: vn.dsai.config.v1.GetConfigHistoryRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	3,  // 19: vn.dsai.config.v1.GetConfigHistoryResponse.versions:type_name -> vn.dsai.config.v1.ConfigVersion
	8,  // 20: vn.dsai.config.v1.ApplyConfigTemplateRequest.template:type_name -> vn.dsai.config.v1.ConfigTemplate
	2,  // 21: vn.dsai.config.v1.GetConfigTemplateRequest.identifier:type_name -> vn.dsai.config.v1.ConfigIdentifier
	9,  // 22: vn.dsai.config.v1.ConfigService.GetConfig:input_type -> vn.dsai.config.v1.GetConfigRequest
	9,  // 23: vn.dsai.config.v1.ConfigService.GetLatestConfig:input_type -> vn.dsai.config.v1.GetConfigRequest
	10, // 24: vn.dsai.config.v1.ConfigService.GetConfigByVersion:input_type -> vn.dsai.config.v1.GetConfigByVersionRequest
	14, // 25: vn.dsai.config.v1.ConfigService.GetConfigHistory:input_type -> vn.dsai.config.v1.GetConfigHistoryRequest
	11, // 26: vn.dsai.config.v1.ConfigService.UpdateConfig:input_type -> vn.dsai.config.v1.UpdateConfigRequest
	12, // 27: vn.dsai.config.v1.ConfigService.PublishVersion:input_type -> vn.dsai.config.v1.PublishVersionRequest
	13, // 28: vn.dsai.config.v1.ConfigService.DeleteConfig:input_type -> vn.dsai.config.v1.DeleteConfigRequest
	16, // 29: vn.dsai.config.v1.ConfigService.ApplyConfigTemplate:input_type -> vn.dsai.config.v1.ApplyConfigTemplateRequest
	17, // 30: vn.dsai.config.v1.ConfigService.GetConfigTemplate:input_type -> vn.dsai.config.v1.GetConfigTemplateRequest
	5,  // 31: vn.dsai.config.v1.ConfigService.GetConfig:output_type -> vn.dsai.config.v1.ScopeConfig
	5,  // 32: vn.dsai.config.v1.ConfigService.GetLatestConfig:output_type -> vn.dsai.config.v1.ScopeConfig
	5,  // 33: vn.dsai.config.v1.ConfigService.GetConfigByVersion:output_type -> vn.dsai.config.v1.ScopeConfig
	15, // 34: vn.dsai.config.v1.ConfigService.GetConfigHistory:output_type -> vn.dsai.config.v1.GetConfigHistoryResponse
	5,  // 35: vn.dsai.config.v1.ConfigService.UpdateConfig:output_type -> vn.dsai.config.v1.ScopeConfig
	3,  // 36: vn.dsai.config.v1.ConfigService.PublishVersion:output_type -> vn.dsai.config.v1.ConfigVersion
	19, // 37: vn.dsai.config.v1.ConfigService.DeleteConfig:output_type -> google.protobuf.Empty
	8,  // 38: vn.dsai.config.v1.ConfigService.ApplyConfigTemplate:output_type -> vn.dsai.config.v1.ConfigTemplate
	8,  // 39: vn.dsai.config.v1.ConfigService.GetConfigTemplate:output_type -> vn.dsai.config.v1.ConfigTemplate
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		EnumInfos:         file_config_v1_config_proto_enumTypes,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
