name: Deploy Demo

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-k3s.yml
    with:
      environment: demo
      k8s_namespace: dsai-demo
      host_alias: demo-server
      use_cloudflared: false
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
